### ISSUE TITLE
Eye tracking analysis via F#

### ISSUE THREAD

**Issue by gileoo** [uncodeference/unmeetup#12]
- **Marcel Ritter**
- **Beginner**
- **15 min**
- **Data analysis, Eye tracking, F#, Medical, Neurology**

# \<Eye tracking analysis via F#>

### One-sentence summary
Notes on an ongoing practical project for plotting, analyzing, classifying, and manual correction of high-resolution eye tracking data with application in Neurology: concepts, implementation, tools/libraries, and algorithms.

### What's the format — is it a case study, a live coding session, a workshop or something else?
Frontal talk, demo, and discussion.

### Tell us more about the talk
Just come and see. :)

### A few words about yourself
**Academic Background:** BSc in Civil Engineering, Msc in Compter Science, PhD candidate in Computer Science at the Interactive Graphics and Simulation Group at the University of Innsbruck specializing in scientific visualization and computational geometry.
**Industrial Background:**
Game development at Clockstone, Head of Software Development at Airborne Hydromapping (AHM).

### Would you be willing to have a Q/A session after the talk?
Yes.

### How can we find you on social media?
www.marcel-ritter.com
Ping me there for skype, telegram, and fb.

**Comment by bemayr** [comment]
Thanks for tracking your last talk!
